services:
  app:
    build: .
    tty: true
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - D1_ACCOUNT_ID=${D1_ACCOUNT_ID}
      - D1_DATABASE_ID=${D1_DATABASE_ID}
      - D1_API_TOKEN=${D1_API_TOKEN}
